# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Beat Choi
email: beatchoi@hellovr.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, world!</h3><h1>DevJournal</h1><h3>Unity3D, Augmented Reality, Virtual Reality</h3>Hope you like it!"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beatchoi.github.io" # the base hostname & protocol for your site
github_username:  beatchoi

# Build settings
markdown: kramdown
